#!/bin/bash

ln -s /usr/lib/terminal/libterminal.so /usr/lib/libterminal.so
chmod -R 755 /usr/include/terminal
chmod -R 755 /usr/lib/terminal
chown -R root:root /usr/lib/terminal
chown -R root:root /usr/lib/terminal
