#!/bin/bash

ln -s /usr/lib/simpleLogger/libsimpleLogger.so /usr/lib/libsimpleLogger.so
chmod -R 755 /usr/include/simpleLogger
chmod -R 755 /usr/lib/simpleLogger
chown -R root:root /usr/lib/simpleLogger
chown -R root:root /usr/lib/simpleLogger
