#!/bin/bash

DIRINCLUDE=/usr/include/simpleLogger
DIRLIB=/usr/lib/simpleLogger

if [ -f "$DIRINCLUDE/simpleLogger.hpp" ]; then
    rm -rf $DIRINCLUDE/simpleLogger.hpp
fi
if [ -f "$DIRLIB/libsimpleLogger.so" ]; then
    rm -rf $DIRLIB/libsimpleLogger.so
fi
if [ -f "/usr/lib/libsimpleLogger.so" ]; then
    rm -rf /usr/lib/libsimpleLogger.so
fi
